### ISSUE TITLE
Add dark mode toggle

### ISSUE THREAD

**Issue by Neilblaze** [Neilblaze/Anyxz#1]
Currently, the UI lacks a dark mode feature ( for example a toggle button). So, a dark mode toggle button will enhance the charm of the project.

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @Neilblaze

**Comment by Neilblaze** [comment]
@subhangi2731 Sure! Go for it :+1: 
Make sure you follow the proper [contribution guidelines](https://github.com/Neilblaze/Anyxz/blob/master/CONTRIBUTING.md).

**Comment by kumarshobhit** [comment]
I would like to work on this issue.

**Comment by Neilblaze** [comment]
@kumarshobhit Go for it!

**Comment by Nivedita967** [comment]
Can I also work on this issue?

**Comment by Neilblaze** [comment]
@Nivedita967 Sure! Go for it :+1:

**Comment by Neilblaze** [comment]
Closing via #29
