### ISSUE TITLE
Make the site responsive for mobile view

### ISSUE THREAD

**Issue by Neilblaze** [Neilblaze/Anyxz#10]
At present, the site is not at all responsive for mobile view. This needs to be fixed so that this can be viewed on most devices. Do note that this project is not optimized for running on mobile devices. So it'll be better if we can populate a preview for mobile devices that it's currently unsupported, or a popup modal for they will be having a bad experience.

There is an open issue stated for the refactoring of code to run on high-end smartphones in #7

**Comment by subhangi2731** [comment]
can you please assign this issue to me? @Neilblaze

**Comment by Neilblaze** [comment]
@subhangi2731 Feel free to raise a pr on it! :)

**Comment by yashgautam9274** [comment]
I want to work on this issue

**Comment by Neilblaze** [comment]
@yashgautam9274 go for it!

**Comment by yashgautam9274** [comment]
is anyone other than me is also workimg on this issue

**Comment by Neilblaze** [comment]
Yes, @subhangi2731 is also working on this issue. This issue doesn't have `assignees`, as the project is under development, thus the most appropriate PR shall be merged!

**Comment by Neilblaze** [comment]
Closed via #28
