### ISSUE TITLE
Improve the SEO of the project site

### ISSUE THREAD

**Issue by Neilblaze** [Neilblaze/Anyxz#11]
The project needs to have updated tags and descriptions so that it improves the SEO of the project.

UPDATE (02.12.20) :-

- PR #17 has been merged.

But this issue shall be kept open as this project needs more SEO improvement. :heavy_check_mark:

**Comment by kumarshobhit** [comment]
I would like to work on it

**Comment by Neilblaze** [comment]
@kumarshobhit The official coding period starts from 1st Dec 2020 i.e tomorrow. I'm assigning to you for now, but remember to raise the PR tomorrow, else it will stand against the rules & regulations of NWoC 2020 & won't be counted!

Best of Luck :+1:

**Comment by kumarshobhit** [comment]
Thank you :)
