### ISSUE TITLE
Make this project PWA

### ISSUE THREAD

**Issue by Neilblaze** [Neilblaze/Anyxz#12]
It'll be great if the project is featured as a Progressive Web App. Add necessary manifest and service-workers to make it a PWA. For images, scale the `favicon.png` & scale it for different resolutions while adding it to the manifest file.

**Comment by KerinPithawala** [comment]
Can I work on this issue?
I have made and loaded manifest.json file and service worker file into index.html on my local machine.
I have on work on scaling favicon.png.

**Comment by Neilblaze** [comment]
@Kerveyfelix Yeah sure! Go for it :)
