### ISSUE TITLE
Add an issue template to the project

### ISSUE THREAD

**Issue by Neilblaze** [Neilblaze/Anyxz#2]

**Comment by Pranav016** [comment]
I would like to work on this issue.

**Comment by Neilblaze** [comment]
@Pranav016 Go for it! :+1:

**Comment by Pranav016** [comment]
I should add two templates, one for bug report and other for feature request, right? @Neilblaze

**Comment by Pranav016** [comment]
I should add two templates, one for bug report and one for feature request, right? @Neilblaze

**Comment by Neilblaze** [comment]
@Pranav016 yes!

**Comment by Neilblaze** [comment]
Closing via #27
