### ISSUE TITLE
update the README.md

### ISSUE THREAD

**Issue by Neilblaze** [Neilblaze/Anyxz#4]
Customize the README file, feel free to add any design inspirations. Some of them include -

- Adding Images (.gif / .png)
- Adding Badges
- Anything beautiful

**Comment by Pranav016** [comment]
I would like to work on this issue.

**Comment by Neilblaze** [comment]
Go for it! :+1: 
Make sure to follow the [contribution guidelines](https://github.com/Neilblaze/Anyxz/blob/master/CONTRIBUTING.md).

**Comment by yashgautam9274** [comment]
i want to work on this issue

**Comment by chehak123** [comment]
Can I work on it?

**Comment by Pranav016** [comment]
Sorry guys, @chehak123 @yashgautam9274 . Already started working on this.

**Comment by Neilblaze** [comment]
@yashgautam9274 @chehak123 join the Anyxz [Gitter channel](https://gitter.im/Anyxz/community) to discuss & create new issues. But for now, feel free to pick up any other issues.

**Comment by Neilblaze** [comment]
Closed via #20
