### ISSUE TITLE
Google + icon not working || Bug report

### ISSUE THREAD

**Issue by Pranav016** [Neilblaze/Anyxz#42]
**Describe the bug**
Since Google+ has been deprecated by Google hence the icon/button leads to nowhere.

**To Reproduce**
1. Click the Google+ icon.

**Suggested Changes-**
I would like to make a PR to add another social media button for the web app or just to remove the Google+ button.

I would like to work on this under **NWoC**

**Comment by Neilblaze** [comment]
Good catch @Pranav016 . Feel free to remove the `g+` social icon.

**Comment by Neilblaze** [comment]
Closed via #44
